//
// Created by sspc on ۲۰۲۰/۵/۶.
//

#ifndef INHERITANCE_POLYMORPHISM_JSON1_JSONELEMENT_HPP
#define INHERITANCE_POLYMORPHISM_JSON1_JSONELEMENT_HPP


class jsonElement {

};


#endif //INHERITANCE_POLYMORPHISM_JSON1_JSONELEMENT_HPP
