before_install: 
  - "eval \"${MATRIX_EVAL}\""
language: cpp
matrix: 
  include: 
    - 
      before_install: 
        - "sudo apt-get update"
        - "sudo apt-get install -y clang-format"
      env: 
        - "MATRIX_EVAL=\"TESTENV=lint && STYLE=LLVM\""
      os: linux
      script: 
        - "find . -name *.h -exec bash -c 'cmp <(clang-format --style=LLVM $0) $0' {} \\;"
        - "find . -name *.hpp -exec bash -c 'cmp <(clang-format --style=LLVM $0) $0' {} \\;"
        - "find . -name *.c -exec bash -c 'cmp <(clang-format --style=LLVM $0) $0' {} \\;"
        - "find . -name *.cpp -exec bash -c 'cmp <(clang-format --style=LLVM $0) $0' {} \\;"
    - 
      before_install: 
        - "sudo apt-get update"
        - "sudo apt-get install -y g++ make libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev"
      env: 
        - "MATRIX_EVAL=\"TESTENV=build && CC=gcc && CXX=g++\""
      os: linux
      script: 
        - make
    - 
      addons:
        homebrew:
          packages:
            - gcc
            - sdl2
            - sdl2_image
            - sdl2_mixer
            - sdl2_ttf
          update: true
      env: 
        - "MATRIX_EVAL=\"TESTENV=build && CC=gcc-9 && CXX=g++-9\""
      os: osx
      script: 
        - make
